# Etapa de build
FROM node:22.14-alpine as build

WORKDIR /app

# Aceita variáveis de ambiente como argumentos de build
ARG VITE_API_BASE_URL
ARG VITE_APP_TOKEN
ARG VITE_TEAM_PADEIRINHO
ARG VITE_TEAM_GARCOM
ARG VITE_TEAM_CONFEITEIROS
ARG VITE_TEAM_JACKFRUIT
ARG VITE_TEAM_MILHARAL
ARG VITE_TEAM_RAIO
ARG VITE_TEAM_APAE
ARG VITE_TEAM_DTM
ARG VITE_TEAM_PREFEITO
ARG VITE_TEAM_FREELANCER
ARG VITE_TEAM_CHEFE
ARG VITE_ID_CALMAKARAI
ARG VITE_TEAM_ADVERTISER
ARG VITE_TEAM_STAFF
ARG VITE_TEAM_KFFC
ARG VITE_TEAM_SAPOCULEANO
ARG VITE_TEAM_GREENSKY

# Transforma ARGs em ENVs para o build do Vite poder usá-las
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL
ENV VITE_APP_TOKEN=$VITE_APP_TOKEN
ENV VITE_TEAM_PADEIRINHO=$VITE_TEAM_PADEIRINHO
ENV VITE_TEAM_GARCOM=$VITE_TEAM_GARCOM
ENV VITE_TEAM_CONFEITEIROS=$VITE_TEAM_CONFEITEIROS
ENV VITE_TEAM_JACKFRUIT=$VITE_TEAM_JACKFRUIT
ENV VITE_TEAM_MILHARAL=$VITE_TEAM_MILHARAL
ENV VITE_TEAM_RAIO=$VITE_TEAM_RAIO
ENV VITE_TEAM_APAE=$VITE_TEAM_APAE
ENV VITE_TEAM_DTM=$VITE_TEAM_DTM
ENV VITE_TEAM_PREFEITO=$VITE_TEAM_PREFEITO
ENV VITE_TEAM_FREELANCER=$VITE_TEAM_FREELANCER
ENV VITE_TEAM_CHEFE=$VITE_TEAM_CHEFE
ENV VITE_ID_CALMAKARAI=$VITE_ID_CALMAKARAI
ENV VITE_TEAM_ADVERTISER=$VITE_TEAM_ADVERTISER
ENV VITE_TEAM_STAFF=$VITE_TEAM_STAFF
ENV VITE_TEAM_KFFC=$VITE_TEAM_KFFC
ENV VITE_TEAM_SAPOCULEANO=$VITE_TEAM_SAPOCULEANO
ENV VITE_TEAM_GREENSKY=$VITE_TEAM_GREENSKY

COPY package*.json ./
RUN npm install

COPY . .
RUN printenv | grep VITE_
RUN npm run build

# Etapa de produção com Nginx
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
