export interface RowData {
  status: string
  name: string
  faction: string
  class: string
  source: string
  advertiser: string
  collectedBy: string
  inGroup: string
  paidFull: string
  note: string
  actions: string
}

export const buyersData: RowData[] = [
  {
    status: '',
    name: 'Player1-Azralon',
    faction: 'Alliance',
    class: 'Warrior',
    source: 'Source',
    advertiser: 'Advertiser1',
    collectedBy: 'Encrypted',
    inGroup: 'check',
    paidFull: 'check',
    note: 'bundle',
    actions: '',
  },
  {
    status: '',
    name: 'Player2-Stormrage',
    faction: 'Horde',
    class: 'Paladin',
    source: 'Source',
    advertiser: 'Advertiser1',
    collectedBy: 'Encrypted',
    inGroup: 'check',
    paidFull: 'uncheck',
    note: '',
    actions: '',
  },
  {
    status: '',
    name: 'Player3-Stormrage',
    faction: 'Horde',
    class: 'Hunter',
    source: 'Source',
    advertiser: 'Advertiser1',
    collectedBy: 'Encrypted',
    inGroup: 'check',
    paidFull: 'check',
    note: '',
    actions: '',
  },
  {
    status: '',
    faction: 'Alliance',
    name: 'Player4-Area52',
    class: 'Rogue',
    source: 'Source',
    advertiser: 'Advertiser2',
    collectedBy: 'Encrypted',
    inGroup: 'uncheck',
    paidFull: 'uncheck',
    note: 'bundle',
    actions: '',
  },
  {
    status: '',
    name: 'Player5-Moonguard',
    faction: 'Horde',
    class: 'Priest',
    source: 'Source',
    advertiser: 'Advertiser2',
    collectedBy: 'Encrypted',
    inGroup: 'check',
    paidFull: 'check',
    note: 'bundle',
    actions: '',
  },
  {
    status: '',
    name: 'Player6-Illidan',
    faction: 'Alliance',
    class: 'Shaman',
    source: 'Source',
    advertiser: 'Advertiser3',
    collectedBy: 'Encrypted',
    inGroup: 'check',
    paidFull: 'check',
    note: 'bundle',
    actions: '',
  },
  {
    status: '',
    name: 'Player7-Area52',
    faction: 'Alliance',
    class: 'Mage',
    source: 'Source',
    advertiser: 'Advertiser1',
    collectedBy: 'Encrypted',
    inGroup: 'check',
    paidFull: 'check',
    note: 'bundle',
    actions: '',
  },
  {
    status: '',
    name: 'Player8-Goldrin',
    faction: 'Horde',
    class: 'Warlock',
    source: 'Source',
    advertiser: 'Advertiser2',
    collectedBy: 'Encrypted',
    inGroup: 'check',
    paidFull: 'check',
    note: '',
    actions: '',
  },
  {
    status: '',
    name: 'Player9-Nemesis',
    faction: 'Horde',
    class: 'Monk',
    source: 'Source',
    advertiser: 'Advertiser2',
    collectedBy: 'Encrypted',
    inGroup: 'check',
    paidFull: 'check',
    note: '',
    actions: '',
  },
  {
    status: '',
    name: 'Player10-Illidan',
    faction: 'Horde',
    class: 'Druid',
    source: 'Source',
    advertiser: 'Advertiser3',
    collectedBy: 'Encrypted',
    inGroup: 'check',
    paidFull: 'check',
    note: 'bundle',
    actions: '',
  },
  {
    status: '',
    name: 'Player11-Bartilhas',
    faction: 'Alliance',
    class: 'Demon Hunter',
    source: 'Source',
    advertiser: 'Advertiser2',
    collectedBy: 'Encrypted',
    inGroup: 'check',
    paidFull: 'check',
    note: '',
    actions: '',
  },
  {
    status: '',
    name: 'Player12-Ragnaros',
    faction: 'Alliance',
    class: 'Death Knight',
    source: 'Source',
    advertiser: 'Advertiser1',
    collectedBy: 'Encrypted',
    inGroup: 'check',
    paidFull: 'check',
    note: '',
    actions: '',
  },
  {
    status: '',
    name: 'Player13-Thrall',
    faction: 'Alliance',
    class: 'Evoker',
    source: 'Source',
    advertiser: 'Advertiser3',
    collectedBy: 'Encrypted',
    inGroup: 'check',
    paidFull: 'check',
    note: 'bundle',
    actions: '',
  },
]
