name: Deploy para Fly.io

on:
  push:
    branches:
      - main # ou a branch que você usa para deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instala Fly.io CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Login na Fly.io
        run: flyctl auth login --access-token "$FLY_API_TOKEN"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Build e Deploy
        run: |
          flyctl deploy \
            --build-arg VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }} \
            --build-arg VITE_APP_TOKEN=${{ secrets.VITE_APP_TOKEN }} \
            --build-arg VITE_TEAM_PADEIRINHO=${{ secrets.VITE_TEAM_PADEIRINHO }} \
            --build-arg VITE_TEAM_GARCOM=${{ secrets.VITE_TEAM_GARCOM }} \
            --build-arg VITE_TEAM_CONFEITEIROS=${{ secrets.VITE_TEAM_CONFEITEIROS }} \
            --build-arg VITE_TEAM_JACKFRUIT=${{ secrets.VITE_TEAM_JACKFRUIT }} \
            --build-arg VITE_TEAM_MILHARAL=${{ secrets.VITE_TEAM_MILHARAL }} \
            --build-arg VITE_TEAM_RAIO=${{ secrets.VITE_TEAM_RAIO }} \
            --build-arg VITE_TEAM_APAE=${{ secrets.VITE_TEAM_APAE }} \
            --build-arg VITE_TEAM_DTM=${{ secrets.VITE_TEAM_DTM }} \
            --build-arg VITE_TEAM_PREFEITO=${{ secrets.VITE_TEAM_PREFEITO }} \
            --build-arg VITE_TEAM_FREELANCER=${{ secrets.VITE_TEAM_FREELANCER }} \
            --build-arg VITE_TEAM_CHEFE=${{ secrets.VITE_TEAM_CHEFE }} \
            --build-arg VITE_ID_CALMAKARAI=${{ secrets.VITE_ID_CALMAKARAI }} \
            --build-arg VITE_TEAM_ADVERTISER=${{ secrets.VITE_TEAM_ADVERTISER }} \
            --build-arg VITE_TEAM_STAFF=${{ secrets.VITE_TEAM_STAFF }} \
            --build-arg VITE_TEAM_KFFC=${{ secrets.VITE_TEAM_KFFC }} \
            --build-arg VITE_TEAM_SAPOCULEANO=${{ secrets.VITE_TEAM_SAPOCULEANO }} \
            --build-arg VITE_TEAM_GREENSKY=${{ secrets.VITE_TEAM_GREENSKY }} \
